Update Runner CommitExtractor.yml

diff --git a/.github/workflows/Runner CommitExtractor.yml b/.github/workflows/Runner CommitExtractor.yml
--- a/.github/workflows/Runner CommitExtractor.yml
+++ b/.github/workflows/Runner CommitExtractor.yml
@@ -2,15 +2,15 @@ name: Runner CommitExtractor
 
 on:
   workflow_dispatch:
-  workflow_run:
-    workflows: ["Runner UnmaskAliases", "Trigger Secondo avvio CommitExtractor"]
-    types:
-      - completed
+#  workflow_run:
+#    workflows: ["Runner UnmaskAliases", "Trigger Secondo avvio CommitExtractor"]
+#    types:
+#      - completed
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Runner UnmaskAliases') || (github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.name == 'Trigger Secondo avvio CommitExtractor') }}
+#    if: ${{ (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.name == 'Runner UnmaskAliases') || (github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.name == 'Trigger Secondo avvio CommitExtractor') }}
 
     steps:
     - name: Checkout main repo
@@ -45,14 +45,19 @@ jobs:
       run: | 
         mkdir -p developersInactivityAnalysis/logs
         mkdir -p developersInactivityAnalysis/Organizations
-        if [ -f "output/Commit_Extraction_${{ vars.OWNER }}.log" ]; then
-           echo "Ci sono state altre esecuzioni, recupero i file..."
-           mv output/Commit_Extraction_${{ vars.OWNER }}.log developersInactivityAnalysis/logs
-           mv output/${{ vars.OWNER }} developersInactivityAnalysis/Organizations
-        else
+        if [ -f "appoggio/Commit_Extraction_${{ vars.OWNER }}.log" ]; then
+           echo "C'è già un esecuzione in corso, recupero i file..."
+           mv appoggio/Commit_Extraction_${{ vars.OWNER }}.log developersInactivityAnalysis/logs
+           mv appoggio/${{ vars.OWNER }} developersInactivityAnalysis/Organizations
+           
+        elif [ -f "output/Commit_Extraction_${{ vars.OWNER }}.log" ]; then
+           echo "Nessuna esecuzione in corso, ma ce ne sono state già altre, recupero i file..."
+           cp -r output/${{ vars.OWNER }} developersInactivityAnalysis/Organizations
+           cp output/Commit_Extraction_${{ vars.OWNER }}.log developersInactivityAnalysis/logs
+        else 
            echo "Questa è la prima esecuzione."
-           cp -r output/${{ vars.OWNER }} developersInactivityAnalysis/Organizations       
         fi
+      #mkdir -p developersInactivityAnalysis/Organizations/${{ vars.OWNER }} se non lo crea da solo mettere prima di fi
 
     - name: Run Python script CommitExtractor.py
       env:
